export default{
    customer_login:'.header-bar__module.header-bar__module--list #customer_login_link',
    submit:'#customer_login input[type="submit"]',
    getProduct : '.grid .grid__item > div > div >div:nth-child(3) > div',
    getProduct_title:'.grid .grid__item > div > div >div:nth-child(3) .grid-link__title',
    wishlist:'.swym-button-bar > div > button',
    wishlist_modal : 'a[href="#swym-wishlist"]',
    add_to_wishlist:'.swym-add-btn',
    list : '.swym-wishlist-selector > button',
    title:'.swym-wishlist-grid > a > .swym-is-button .swym-title',
    close:'.swym-modal-content .swym-close-btn',
    quantity:'.swym-product-quantity > div',
    add_quantity:'.swym-product-quantity > button',
    product_in_list:'.swym-wishlist-grid > a',
    share_list:'.swym-button-actions .swym-share-btn',
    share:'.swym-share-email-button-container > button',
    my_wishlist:'.swym-wishlist-selector > button .swym-wishlist-name',
    actions:'.swym-secondary-actions > button',
    add_to_cart:'.swym-action-button-container .swym-wishlist-add-to-cart-btn',
    collaborator : '.swym-wishlist-context-menu-content > button',
    add_collaborator:'.swym-action-button-container > button',
    new_list:'.swym-editable-list-name input',
    label_name : '.swym-group-by-label .swym-group-by-label-name',
    list_name:'.swym-wishlist-selector > button .swym-wishlist-header > div',
    variant:'.swym-select .swym-value',
    note:'.swym-wishlist-selector > button .swym-popover-button',
    note_text:'.swym-popover-button > button .swym-value',
    collaborator_email:'.swym-input-inner-container #swym-email',
    total_list_value:'.swym-wishlist-value-container .swym-wishlist-value-count',
    back_btn:'.swym-wishlist-detail-htc-user > div .swym-action-bar .swym-back-btn'
}